version: '3'
services:
  api:
    build: "https://github.com/OIT-UOG/specify-webportal-installer.git#vue-rewrite"
    restart: always
    volumes:
      - ./build/:/usr/local/tomcat/webapps/apps/:ro
    environment:
      - VIRTUAL_PORT=8080
  nginx:
    image: "jwilder/nginx-proxy"
    restart: always
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${SP_CERTS_PATH}:/etc/nginx/certs
