version: '3'
services:
  web:
    build: "https://github.com/OIT-UOG/specify-webportal-installer.git#vue-rewrite"
    volumes:
      - ./build/:/usr/local/tomcat/webapps/apps/:ro
    ports:
      - "80:8080"