version: '3'
services:
  api:
    build: "https://github.com/OIT-UOG/specify-webportal-installer.git${SPECIFY_API_BRANCH}"
    volumes:
      - build:/usr/local/tomcat/webapps/apps/:ro
      - root:/usr/local/tomcat/webapps/ROOT/:ro
    environment:
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=${HOSTNAME}
      - LETSENCRYPT_HOST=${HOSTNAME}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    restart: on-failure
  
  api_middleman:
    build: "https://github.com/OIT-UOG/Specify-API-Middleman-API.git${MIDDLEMAN_BRANCH}"
    ports:
      - "8000"
    environment:
      - API_URL=http://api:8080
      - APP_URL=$HOSTNAME
      - VIRTUAL_PORT=8000
      - VIRTUAL_HOST=${API_URL}
      - LETSENCRYPT_HOST=${API_URL}
    restart: on-failure

  frontpage:
    build: "https://github.com/OIT-UOG/specify-vue-frontpage.git${FRONTPAGE_BRANCH}"
    depends_on: 
      - api
    volumes:
      - root:/app/transfer
    command: /bin/sh -c 'npm run build && echo built && while [[ "$$(curl --connect-timeout 5 -s -o /dev/null -w ''%{http_code}'' api:8080/specify-solr/)" != "200" ]]; do echo ..; sleep 5; done; cp -r dist/* transfer && cd transfer && sh insert_google_analytics.sh && echo transferred'

  viewer:
    build: .
    depends_on:
      - api
    environment:
      - MAPS_API_KEY=${MAPS_API_KEY}
      - FORM_URL=${FORM_URL}
      - ISSUE_PAGE_LINK=${ISSUE_PAGE_LINK}
      - API_URL=${API_URL}
    volumes:
      - .env:/app/.env:ro
      - build:/app/build
      - root:/app/transfer:ro
    command: /bin/sh -c 'npm run build && mkdir build/viewer && echo built && while [[ "$$(curl --connect-timeout 5 -s -o /dev/null -w ''%{http_code}'' api:8080/specify-solr/)" != "200" ]]; do echo ..; sleep 5; done; cp -r temp/* build/viewer/ && for f in transfer/*google*; do cp "$$f" build/viewer/; done; cd build/viewer && sh insert_google_analytics.sh && echo transferred'

volumes:
  build:
  root:
  share:

